Extract Strings Github Action
mustang-im/mustang pull request #129
Opened 2024-07-10 18:44 UTC by jermy-c

**Changes**

- Add Github action that extracts strings and pushes the extracted strings back to the repo

**Proposed workflow**

1. Trigger Github Action `Extract Strings`, this leaves extracted strings empty so it's safe to have them in the `master` branch
2. Weblate receives changes and triggers automatic translation using desired translation engine e.g. LibreTranslate, DeepL or Google Cloud Translation Basic
3. Translated strings are labeled `Automatically translated` and marked as `Needs editing`
4. Translators edit translation and the `Automatically translated` label and `Needs editing` are automatically removed
5. Changes are pushed to `translations` branch
6. Check for ICU Message Format syntax errors on Weblate and create a PR
7. Merge changes into `master`

2024-07-10 19:08 UTC, benbucksch requested changes

2024-07-10 19:08 UTC, benbucksch commented on .github/workflows/extract-strings.yml
> +        git commit -a -m "Extract Strings"
```suggestion
        git config user.name "Bot"
        git config user.email "translate@mustang.im"
        git commit -a -m "Translation: Extract UI strings from code into the English master translation file"
```

2024-07-10 19:08 UTC, benbucksch commented on .github/workflows/extract-strings.yml
> +    - name: Extract Strings
```suggestion
    - name: Extract UI strings to be translated
```

2024-07-10 19:11 UTC, benbucksch commented
We cannot always wait for translators for every string addition. We do not have translators for all languages that are constantly standing waiting. We can hire translators only maybe once per year.

Can we instead use the following workflow?
* Extract strings
* Push to automatic translation
* Add automatic translations into translated files, in the right place
* Commit
* Push to Weblate
* Release
* Let translators double-check (typically many weeks months later)
* Release

2024-07-16 12:18 UTC, benbucksch commented
More concretely, steps 2 and 3 should have their own commands in packages.json. Then, another packages.json command should do steps 1-4 together. Lastly, a github action invokes the command that does steps 1-4, and then makes the git commit, as done here in this PR.

2024-07-16 17:07 UTC, jermy-c commented
Sounds good, will do.

2025-02-19 10:13 UTC, benbucksch commented
Included in #445

2025-02-19 10:13 UTC, closed without merging