ActiveSync: Support for protocol v14.1 and v14.0 - fixes #212
mustang-im/mustang pull request #220
Opened 2024-09-26 22:43 UTC by jermy-c

- Some accounts use protocol v14.0 e.g. personal accounts
- Missing the `cookie: "DefaultAnchorMailbox={ uri encoded email address }"` causes the HTTP 451 response
- Based on [`neil/activesync-version-14.0`](https://github.com/mustang-im/mustang/tree/neil/activesync-version-14.0)

2024-09-26 22:50 UTC, jermy-c commented
I have gotten `ActiveSync Sync status {number}` errors but I'm guessing it's just because I'm testing and making too many requests. And also I've gotten `Request time out` errors.

2024-09-27 19:14 UTC, NeilRashbrook commented
Common Sync error codes:
3. Sync key out of date
4. Request format error
5. Temporary server error
6. invalid request data
7. Change rejected by server
8. Item not found
12. Folder hierarchy changed
16. Retryable server error

2024-09-27 20:34 UTC, jermy-c commented
Thank you for that.

These were the codes I managed to record from yesterday.
```
EASError: ActiveSync Sync status 16
    at ActiveSyncAccount.callEAS (ActiveSyncAccount.ts:229:13)
    at async ActiveSyncFolder.makeSyncRequest (ActiveSyncFolder.ts:116:20)
```
	
```
Uncaught (in promise) EASError: ActiveSync Sync status 3
    at ActiveSyncFolder.makeSyncRequest (ActiveSyncFolder.ts:126:13)
```

```
EASError: ActiveSync Sync status 132
    at ActiveSyncAccount.callEAS (ActiveSyncAccount.ts:229:13)
    at async ActiveSyncFolder.makeSyncRequest (ActiveSyncFolder.ts:116:20)
    at async ActiveSyncFolder.queuedSyncRequest (ActiveSyncFolder.ts:101:14)
    at async ActiveSyncFolder.listMessages (ActiveSyncFolder.ts:148:18)
    at async getFirstMessages (saveConfig.ts:90:5)
```

2024-09-27 20:42 UTC, NeilRashbrook commented
> EASError: ActiveSync Sync status 16

If we get a lot of these then perhaps we should add an automatic retry after 5 seconds?

> Uncaught (in promise) EASError: ActiveSync Sync status 3

This is weird because all of the callers in the ActiveSync code have an `await`, so is the UI forgetting to `await` something?

> EASError: ActiveSync Sync status 132

This is apparently an internal server error, which used to be returned as an HTTP 500 before protocol 14.0; you're likely to encounter a subsequent status 3.

2024-10-04 02:41 UTC, benbucksch requested changes

2024-10-04 02:41 UTC, benbucksch commented on app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
> +      let urls = OAuth2URLs.find(a => a.hostnames.includes(this.hostname));
```suggestion
      let urls = OAuth2URLs.find(a => a.hostnames.includes(this.hostname));
      assert(urls, gt`Could not find OAuth2 config for ${this.hostname}`);
```

2024-10-04 02:41 UTC, benbucksch commented on app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
> +    if (this.authMethod == AuthMethod.OAuth2) {
```suggestion
    if (this.authMethod == AuthMethod.OAuth2) {
      if (!this.oAuth2) {
```

2024-10-04 02:41 UTC, benbucksch commented on app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
> +      await this.oAuth2.login(true);
```suggestion
      }
      await this.oAuth2.login(true);
```

(see `if` above)

2024-10-04 02:42 UTC, benbucksch commented
> Common Sync error codes: 3. Sync key out of date 4. Request format error 5. Temporary server error 6. invalid request data 7. Change rejected by server 8. Item not found 12. Folder hierarchy changed 16. Retryable server error

Could we please make constants or an enum for that?

2024-10-05 19:19 UTC, benbucksch approved these changes

2024-10-05 19:19 UTC, benbucksch commented on app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
> +  version: string;
We should call this `protocolVersion`

2024-10-05 19:25 UTC, benbucksch approved these changes

2024-10-05 19:27 UTC, merged