ActiveSync: No folders fix
mustang-im/mustang pull request #229
Opened 2024-10-08 18:17 UTC by jermy-c

After logging into an ActiveSync account no folders are displayed.

- `listFolders()` was removed in `login()`

2024-10-08 20:54 UTC, jermy-c commented
Even after adding the `listFolders()` it is still not displaying any folders sometimes.

2024-10-08 23:54 UTC, benbucksch commented
>     * `listFolders()` was removed in `login()`

Yes, you did that in 09ace99cd. Note that it had more code in there.

2024-10-08 23:55 UTC, benbucksch requested changes
Note sufficient, see original code.

2024-10-09 20:49 UTC, jermy-c commented
> listFolders() was removed in login()

That was actually removed by merge commit from master 75bf7d453c9fb509e13ad517e255164f0f13b7e1. I did add it back 70af0f18f215c7fc792e6511b478e561aa0d0237 but I didn't add the `verifyLogin()` since in https://github.com/mustang-im/mustang/issues/212#issuecomment-2372289596 mentioned that:

> Also, sorry for the mixup with verifyLogin; originally I was running into the problem that the UI was trying to log in before the account was saved, and I had the bright idea of creating a function called verifyLogin to handle that case, not realising that it already existed

I tried checking out the master branch before the commit was made and I'm still getting the same problem sometimes. And also I'm getting a request timed out error:

```
SetupMail.svelte:215 TimeoutError: Request timed out
    at message.js:153:16
    at new Promise (<anonymous>)
    at WSCall.makeCall (message.js:148:12)
    at JPCWebSocket.callRemote (protocol.js:161:31)
    at Object.postHTTP (obj.js:198:55)
    at ActiveSyncAccount.callEAS (ActiveSyncAccount.ts:179:46)
    at async ActiveSyncAccount.makeRequest (ActiveSyncAccount.ts:273:22)
    at async ActiveSyncAccount.queuedRequest (ActiveSyncAccount.ts:264:14)
    at async ActiveSyncAccount.listFolders (ActiveSyncAccount.ts:288:20)
    at async ActiveSyncAccount.login (ActiveSyncAccount.ts:69:7)
```

I'm guessing the error might be because the request timed out error doesn't throw immediately and you're just waiting for a response and that's why I didn't see any error message from before but you'll have to wait for a while before seeing the message.

2024-10-10 02:50 UTC, benbucksch commented
Neil wrote elsewhere:
> > Also, sorry for the mixup with verifyLogin; originally I was running into the problem that the UI was trying to log in before the account was saved, and I had the bright idea of creating a function called verifyLogin to handle that case, not realising that it already existed

Ah, I see. So the code here would be fine. Thanks for digging this up!

2024-10-10 02:50 UTC, benbucksch approved these changes

2024-10-10 02:51 UTC, merged

2024-10-10 20:07 UTC, NeilRashbrook commented
I don't know whether it's relevant, but I got this error on first login while creating an ActiveSync account:
SetupMail.svelte:216 TypeError: Cannot read properties of undefined (reading 'saveFolder')
    at ActiveSyncFolder.save (Folder.ts:160:24)
    at ActiveSyncAccount.listFolders (ActiveSyncAccount.ts:346:22)
    at async ActiveSyncAccount.login (ActiveSyncAccount.ts:85:5)
    at async saveAndInitConfig (saveConfig.ts:14:3)
    at async onSave (SetupMail.svelte:232:16)
    at async onContinue (SetupMail.svelte:182:24)
    at async HTMLButtonElement.myOnClick (Button.svelte:68:16)

2024-10-10 20:25 UTC, jermy-c commented
> I don't know whether it's relevant, but I got this error on first login while creating an ActiveSync account:

I'm getting a similar issue for OWA also but it also affects calendars:

```
Account.ts:37 Error: To save an event, the calendar needs to be saved first
    at assert (util.ts:4:11)
    at OWAEvent.save (Event.ts:135:5)
    at OWAEvent.save (OWAEvent.ts:123:17)
    at async OWACalendar.getEvents (OWACalendar.ts:152:9)
    at async OWACalendar.listFolder (OWACalendar.ts:73:7)
    at async OWACalendar.listEvents (OWACalendar.ts:27:5)
    at async OWAAccount.login (OWAAccount.ts:118:5)
    at async saveAndInitConfig (saveConfig.ts:14:3)
    at async onSave (SetupMail.svelte:232:16)
    at async onContinue (SetupMail.svelte:182:24)
```

```
error.ts:14 TypeError: Cannot read properties of undefined (reading 'saveFolder')
    at OWAFolder.save (Folder.ts:160:24)
    at EMailCollection.readFolder (EMailCollection.ts:16:25)
    at OWAFolder.readFolder (Folder.ts:57:25)
    at OWAFolder.listMessages (OWAFolder.ts:91:16)
    at getFirstMessages (saveConfig.ts:89:16)
    at saveAndInitConfig (saveConfig.ts:15:3)
    at async onSave (SetupMail.svelte:232:16)
    at async onContinue (SetupMail.svelte:182:24)
    at async HTMLButtonElement.myOnClick (Button.svelte:68:16)
```

2024-10-11 07:44 UTC, benbucksch commented
Sorry guys. This is not a regression of this bug, but of commit 0056359113c4a0701d4e1c2289cb0f52e7b40008 . I'm implementing another database and had to do some refactoring and forgot to test the setup. My bad. Sorry.
@jeremy, could you please try to fix it and make a PR? Should be trivial to fix, please don't spend more than 1h.

10.10.2024 22:08:11 Neil Rashbrook ***@***.***>:

> 
> I don't know whether it's relevant, but I got this error on first login while creating an ActiveSync account:
> SetupMail.svelte:216 TypeError: Cannot read properties of undefined (reading 'saveFolder')
> at ActiveSyncFolder.save (Folder.ts:160:24)
> at ActiveSyncAccount.listFolders (ActiveSyncAccount.ts:346:22)
> at async ActiveSyncAccount.login (ActiveSyncAccount.ts:85:5)
> at async saveAndInitConfig (saveConfig.ts:14:3)
> at async onSave (SetupMail.svelte:232:16)
> at async onContinue (SetupMail.svelte:182:24)
> at async HTMLButtonElement.myOnClick (Button.svelte:68:16)
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/mustang-im/mustang/pull/229#issuecomment-2405949844], or unsubscribe[https://github.com/notifications/unsubscribe-auth/AAORWRI7VYCRZMNXCIHUQKDZ23NCBAVCNFSM6AAAAABPS26IICVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBVHE2DSOBUGQ].
> You are receiving this because you modified the open/close state.
> [Verfolgungsbild][https://github.com/notifications/beacon/AAORWRM44J5ANFELKOLZXPTZ23NCBA5CNFSM6AAAAABPS26IICWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTUPM7QZI.gif]
>

2024-10-11 08:00 UTC, benbucksch commented
See Neil's and my comment in https://github.com/mustang-im/mustang/commit/32c2687493dad9870a00dc7451b734e157bcb511#r147825086

2024-10-11 17:06 UTC, jermy-c commented
> Sorry guys. This is not a regression of this bug, but of commit https://github.com/mustang-im/mustang/commit/0056359113c4a0701d4e1c2289cb0f52e7b40008 . I'm implementing another database and had to do some refactoring and forgot to test the setup. My bad. Sorry.
[@jeremy](https://github.com/jeremy), could you please try to fix it and make a PR? Should be trivial to fix, please don't spend more than 1h.

Neil made a PR for that already at #231

2024-10-11 18:38 UTC, NeilRashbrook commented
@jermy-c I think @benbucksch meant my comment was a regression from 32c687

2024-10-11 18:56 UTC, NeilRashbrook commented
Oh actually this problem is a regression from both commits; 32c2687 broke saving of mail accounts while 0056359 broke saving of address books and calendars. #231 was for a separate regression from 0056359.

2024-10-11 19:01 UTC, jermy-c commented
> @jermy-c I think @benbucksch meant my comment was a regression from [32c2687](https://github.com/mustang-im/mustang/commit/32c2687493dad9870a00dc7451b734e157bcb511)

Ok, thanks. I just noticed but I'm a bit confused by the comment.